<?php

$translations_nl_en = array(

    # index.php
    'Datasetregister' =>  'Dataset Register',
    'Voor alle erfgoeddatasets!' => 'For all heritage datasets!',
	'Het datasetregister geeft inzicht in de beschikbaarheid van datasets in het erfgoedveld en stimuleert daarmee het gebruik van deze datasets.' => 'The dataset register provides insight into the availability of datasets in the heritage field and thus encourages the use of these datasets.',
    'Voor erfgoedinstellingen met datasets' => 'For heritage institutions with datasets',
    'voeg een datasetbeschrijving toe'=>'add a dataset description',
    'Voeg een datasetbeschrijving toe'=>'Add a dataset description',
    'Voor gebruikers van erfgoeddata' => 'For users of heritage data',
    'doorzoek <span id="datasetcount">alle</span> datasetbeschrijvingen' => 'search <span id="datasetcount">all</span> dataset descriptions',
    'Ben je actief met datasets bij een erfgoedinstelling?' => 'Are you active with datasets at a heritage institution?',
    'Maak een datasetbeschrijving' => 'Create a dataset description',
    'Veelgestelde vragen door dataset beheerders' => 'Frequently asked questions by dataset administrators',
    'Ben je op zoek naar erfgoeddatasets?' => 'Are you looking for heritage datasets?',
    'Leer via de Data story hoe te zoeken' => 'Learn how to search via the Data story',
    'Doorzoek alle datasetbeschrijvingen' => 'Search all dataset descriptions',
    'Veelgestelde vragen door dataset gebruikers'=>'Frequently asked questions by dataset users',
    'Ontwikkel je software voor erfgoedinstellingen?' => 'Do you develop software for heritage institutions?',
    'Eisen gesteld aan datasetbeschrijvingen' => 'Requirements for dataset descriptions',
    'Valideer een datasetbeschrijving via URL' => 'Validate a dataset description via URL',
    'API-documentatie' => 'API documentation',
    'Veelgestelde vragen door ontwikkelaars' => 'Developer FAQ',

    # header.php
    'Het datasetregister geeft inzicht (voor geïnteresseerden, onderzoekers, andere erfgoedinstellingen en softwareontwikkelaars) in de beschikbaarheid van datasets in het erfgoedveld en stimuleert daarmee het gebruik van deze datasets.' => 'The dataset register provides insight (for interested parties, researchers, other heritage institutions and software developers) into the availability of datasets in the heritage field and thus encourages the use of these datasets.',
    'Naar de startpagina van het Datasetregister' => 'To the start page of the Dataset Register',
    'Maak'=>'Create',
    'Valideer'=>'Validate',
    'Meld aan'=>'Submit',
    'Doorzoek'=>'Search',
    'Veel gestelde vragen'=>'FAQ',
    'datasetbeheerders bij erfgoed&shy;instellingen'=>'dataset managers at heritage institutions',
    'datasetgebruikers bij erfgoed&shy;instellingen en aggregators'=>'dataset users at heritage institutions and aggregators',
    'ontwikkelaars van erfgoed software'=>'heritage software developers',
    'Sluiten'=>'Close',

    # footer.php
    'Privacyverklaring'=>'Privacy statement',
    'Contact'=>'Contact',
    'Het Datasetregister is het resultaat van de samenwerking binnen het Netwerk Digitaal Erfgoed en wordt beheerd en onderhouden door het Nationaal Archief.'=>'The Dataset Register is the result of collaboration within the Digital Heritage Network and is managed and maintained by the National Archives.',
    'Volg het Netwerk Digitaal Erfgoed via'=>'Follow the Digital Heritage Network via',

    # faq.php
    'Veelgestelde vragen over het Datasetregister'=> 'Frequently asked questions about the Dataset Register',
    'De veelgestelde vragen zijn opgedeeld per doelgroep'=>'The frequently asked questions are divided by target group',
    'dataset beheerders bij erfgoedinstellingen'=>'dataset managers at heritage institutions',
    'dataset gebruikers bij erfgoedinstellingen en aggregators'=>'dataset users at heritage institutions and aggregators',
    'ontwikkelaars die erfgoed datasets willen vinden'=>'developers who want to find heritage datasets',

    # faq-beheerders.php
    'Veelgestelde vragen over het Datasetregister door dataset beheerders bij erfgoedinstellingen'=>'Frequently asked questions about the Dataset Register by dataset managers at heritage institutions',
    'Wat is een dataset?'=>'What is a data set?',
    'Een dataset (of gegevensverzameling) is een verzameling van gegevens (data of metadata). In de context van erfgoedinstellingen kun je hierbij denken aan de data van/over erfgoedobjecten, zoals een catalogus, een set museumobjecten of een collectie van archieven of nadere toegangen. Deze (meta)data wordt veelal in een archiefbeheer- of collectieregistratiesysteem beheerd en in de een of andere vorm via de eigen website toegankelijk gemaakt aan haar gebruikers. De data kan ook worden gedeeld voor hergebruik, door een dienstenportaal of aggregator. Het systeem van de erfgoedinstelling dient hiervoor de data via een datadump (export) of API beschikbaar te stellen.'=>'A dataset (or dataset) is a collection of data (data or metadata). In the context of heritage institutions, you can think of data from/about heritage objects, such as a catalog, a set of museum objects or a collection of archives or further accesses. This (meta) data is often managed in an archive management or collection registration system and made accessible to its users in one form or another via its own website. The data can also be shared for reuse, through a service portal or aggregator. The heritage institution\'s system must make the data available for this purpose via a data dump (export) or API.',
    'Wat is een datasetbeschrijving?'=>'What is a dataset description?',
    'Een dataset dient zelf ook weer voorzien te worden van metadata. De beschrijving is dus data over de dataset.'=>'A dataset itself also needs to be provided with metadata. The description is therefore data about the dataset.',
    'Waarom is een datasetbeschrijving belangrijk?'=>'Why is a dataset description important?',
    'Net als erfgoedcollecties is het van belang dat datasets ook vindbaar zijn. Een rijke datasetbeschrijving op een standaard wijze helpt bij het vindbaar maken van de dataset. De datasetbeschrijvingen, mits vormgegeven in een standaard formaat, zijn niet alleen "voer" voor het Datasetregister. Ook zoekmachines zoals Google herkennen datasetbeschrijvingen en maken deze onder andere doorzoekbaar via <a href="https://datasetsearch.research.google.com/">Dataset Search</a>. Hoe beter datasets zijn beschreven en deze beschrijvingen vindbaar zijn, hoe beter hergebruikers de datasets kunnen vinden en daarmee gebruiken en wellicht ook koppelen.'=>'Just like heritage collections, it is important that datasets are also findable. A rich dataset description in a standard way helps to make the dataset discoverable. The dataset descriptions, provided they are formatted in a standard format, are not just "feed" for the Dataset register. Search engines such as Google also recognize dataset descriptions and make them searchable via <a href="https://datasetsearch.research.google.com/">Dataset Search</a>. The better datasets are described and these descriptions can be found, the better re-users can find and use the datasets and possibly also link them.',
    'Welke informatie bevat een datasetbeschrijving?'=>'What information does a dataset description contain?',
    'Een datasetbeschrijving bevat informatie die de dataset beschrijft, zoals een identificatie (URI), een naam, een inhoudsbeschrijving, een licentie, een taal en een data-eigenaar (de maker). Aanvullend op de verplichte informatie elementen kan er informatie worden gegeven over de creatiedatum, publicatiedatum, versie, contact informatie, dekking qua plaats/gebied en tijd/periode, steekwoorden en genre.'=>'A dataset description contains information that describes the dataset, such as an identifier (URI), a name, a content description, a license, a language, and a data owner (the creator). In addition to the mandatory information elements, information can be given about the creation date, publication date, version, contact information, coverage in terms of place/area and time/period, keywords and genre.',
    'De dataset kan op verschillende manieren aangeboden worden, dit wordt de distributie genoemd. Het kan een datadump zijn die gedownload kan worden in een of ander formaat of een API die bevraagbaar is, bijvoorbeeld een SPARQL endpoint. De informatie over distributies bestaat uit een URL, een formaat en soort, en optioneel een licentie, omschrijving, taal, publicatiedatum, wijzigingsdatum en bestandsgrootte.'=>'The dataset can be presented in different ways, this is called the distribution. It can be a data dump that can be downloaded in some format or an API that is queryable, for example a SPARQL endpoint. The information about distributions consists of a URL, a format and type, and optionally a license, description, language, publication date, modification date and file size.',
    'Een set van datasetbeschrijvingen wordt een datasetcatalogus genoemd. Het geeft een totaal overzicht van de beschikbare datasets van een organisatie.'=>'A set of dataset descriptions is called a dataset catalog. It provides a total overview of the available datasets of an organization.',
    'Waar wordt een datasetbeschrijving gepubliceerd?'=>'Where is a dataset description published?',
    'Net als het publiceren van de dataset is het aan de erfgoedinstelling om de datasetbeschrijving te publiceren. Informatie, leesbaar voor mens en machine, dient online beschikbaar te worden gemaakt.'=>'Just like publishing the dataset, it is up to the heritage institution to publish the dataset description. Information, readable by man and machine, must be made available online.',
    'Als het publiceren niet via de eigen infrastructuur zoals CMS lukt, dan kan er gebruik worden gemaakt van de "publication service" <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register-entries">Dataset Register entries</a> via Github.'=>'If publishing via your own infrastructure such as CMS does not work, you can use the "publication service" <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register-entries"> Dataset Register entries</a> via Github.',
    'Hoe kan ik mijn datasetbeschrijving controleren?'=>'How can I check my dataset description?',
    'Via de REST API kan de datasetbeschrijving worden gecontroleerd of deze voldoet aan de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a>.'=>'Via the REST API, the dataset description can be checked whether it complies with the <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a>.',
    'Je kunt de datasetbeschrijving ook controleren met behulp van de algemenere <a href="https://validator.schema.org/">Schema Markup Validator</a>. Geef hier de URL op van de (online) pagina waarin de datasetbeschrijving is opgenomen of plak een codefragment om de test uit te voeren.'=>'You can also check the dataset description using the more general <a href="https://validator.schema.org/">Schema Markup Validator</a>. Enter here the URL of the (online) page that contains the dataset description or paste a code snippet to run the test.',
    'Wat is het Datasetregister?'=>'What is the Dataset Register?',
    'Het doel van het Datasetregister is om inzicht te krijgen in erfgoeddatasets. Erfgoedinstellingen worden aangemoedigd om datasets aan te bieden vanuit hun systeem, deze datasets te beschrijven en online te publiceren en om de URL\'s van datasetbeschrijvingen aan te melden bij het Datasetregister. Het Datasetregister haalt de datasetbeschrijvingen op waardoor er een totaalbeeld ontstaat van wat beschikbaar is.'=>'The purpose of the Dataset Register is to gain insight into heritage datasets. Heritage institutions are encouraged to provide datasets from their system, describe these datasets and publish them online and to submit the URLs of dataset descriptions to the Dataset Register. The Dataset Register retrieves the dataset descriptions, creating an overall picture of what is available.',
    'Hoe kan ik een datasetbeschrijving aanmelden bij het Datasetregister?'=>'How can I submit a dataset description in the Datasets Register?',
    'Idealiter vindt de aanmelding van een datasetbeschrijving (automatisch) plaats via het eigen beheersysteem.'=>'Ideally, the registration of a dataset description takes place (automatically) via your own management system.',
    'Een URL van een datasetbeschrijving (die dus door de erfgoedinstelling is gepubliceerd) kan bij het Datasetregister worden aangemeld. Na aanmelding zal het Datasetregister de datasetbeschrijving controleren en ophalen. Het Datasetregister zal dit frequent herhalen om wijzigingen of verwijderingen op te merken om het Datasetregister hiermee bij te werken.'=>'A URL of a dataset description (which has therefore been published by the heritage institution) can be registered with the Dataset Register. After registration, the Dataset Register will check and retrieve the dataset description. The Dataset Register will repeat this frequently to notice changes or deletions to update the Dataset Register.',
    'Voor erfgoedinstellingen die nog niet in staat zijn om een datasetbeschrijving vanuit het eigen systeem te genereren biedt het Netwerk Digitaal Erfgoed een <a href="/form.php">formulier aan voor het maken van een datasetbeschrijving</a>. Het resultaat is een stuk JSON-LD die op de eigen website of ander platform gepubliceerd kan worden.'=>'For heritage institutions that are not yet able to generate a dataset description from their own system, the Digital Heritage Network offers a <a href="/form.php?lang=en">form for creating a dataset description</a>. The result is a piece of JSON-LD that can be published on your own website or other platform.',
    'Hoe kan ik het Datasetregister uitproberen?'=>'How can I try out the Dataset Register?',
    'Via deze website, een demonstrator voor de Datasetregister API, kun je datasetbeschrijvingen aanmelden en doorzoeken. Deze demonstrator maakt gebruik van de <a href="https://datasetregister.netwerkdigitaalerfgoed.nl/api/">REST API</a>, die je ook direct kunt aanspreken.'=>'Via this website, a demonstrator for the Datasetregister API, you can submit and search dataset descriptions. This demonstrator uses the <a href="https://datasetregister.netwerkdigitaalerfgoed.nl/api/">REST API</a>, which you can also address directly.',
    'Wie maakt en beheert het Datasetregister?'=>'Who creates and manages the Dataset Register?',
    'Het Datasetregister is gemaakt door de samenwerkende erfgoedinstellingen in het <a href="https://www.netwerkdigitaalerfgoed.nl/">Netwerk Digitaal Erfgoed</a> en wordt beheerd en onderhouden door het <a href="https://www.nationaalarchief.nl/">Nationaal Archief</a>. Het Nationaal Archief staat in voor de werking en beschikbaarheid van het Datasetregister.'=>'The Dataset Register was created by the collaborating heritage institutions in the <a href="https://www.netwerkdigitaalerfgoed.nl/">Network Digital Heritage</a> and is managed and maintained by the <a href="https:// www.nationaalarchief.nl/">National Archives</a>. The National Archives is responsible for the operation and availability of the Dataset Register.',
    'Wat is de status van het Datasetregister?'=>'',
    'Het Datasetregister is klaar om verder gevuld te worden. De requirements, API en deze website zijn stabiel en worden op basis van feedback van gebruikers en leveranciers verfijnd.'=>'',
    'Kan ik al aan de slag met datasetbeschrijvingen maken?'=>'Can I get started with creating dataset descriptions?',
    'Jazeker! De definitie van wat voor informatie er in de datasetbeschrijving opgenomen dient te worden ligt vast. Oook het mechanisme om datasetbeschrijvingen aan te melden en de opslag van datasetbeschrijvingen in een triplestore zijn operationeel. Als dataset beheerder kun je dus beginen met het beschrijven van de beschikbare datasets, bekijken waar de datasetbeschrijvingen kunnen worden gepubliceerd en deze aanmelden. Veelal betekent dit ook contact zoeken met uw software leverancier.'=>'Yes, of course! The definition of what information should be included in the dataset description is fixed. Also the mechanism to register dataset descriptions and the storage of dataset descriptions in a triplestore are operational. As a dataset administrator you can therefore start by describing the available datasets, see where the dataset descriptions can be published and register them. This often also means contacting your software supplier.',
    'Via een formulier kun je handmatig een datasetbeschrijving maken. Hiermee krijg je een idee over welke informatie benodigd <i>en</i> voorhanden is binnen systeem en organisatie. Vanuit het oogpunt van onderhoud is een oplossing vanuit uw systeem duurzamer.'=>'You can manually create a dataset description using a form. This gives you an idea of what information is required <i>and</i> within the system and organization. From a maintenance point of view, a solution from your system is more sustainable.',
    'Als je de datasetbeschrijvingen al online publiceert, dan zullen zoekmachines zoals Google\'s <a href="https://datasetsearch.research.google.com/">Dataset Search</a> de datasets wellicht al oppikken!'=>'If you already publish the dataset descriptions online, then search engines like Google\'s <a href="https://datasetsearch.research.google.com/">Dataset Search</a> may already be picking up the datasets!',
    'We horen ook graag wat je ervan vindt. Bijvoorbeeld: is duidelijk welke informatie in de datasetbeschrijving thuishoort? Is duidelijk hoe je de datasetbeschrijvingen gevuld krijgt, qua proces en qua gebruikte software?'=>'We\'d also love to hear what you think. For example: is it clear which information belongs in the dataset description? Is it clear how you fill the dataset descriptions, in terms of process and software used?',
    'Ga je aan de slag?'=>'Are you getting started?',
    'Ga je aan de slag met het publiceren van datasetbeschrijvingen en de API op het Datasetregister, laat het weten, zodat we je op de hoogte kunnen houden van ontwikkelingen, updates en beschikbaarheid.'=>'If you are going to start publishing dataset descriptions and the API on the Dataset Register, let us know so that we can keep you informed of developments, updates and availability.',
    'Meer weten?'=>'Do you want to know more?',
    'Heb je vragen en/of opmerkingen over de werking van het Datasetregister neem dan contact op met <a href="mailto:info@nationaalarchief.nl?subject=Datasetregister">info@nationaalarchief.nl</a>.'=>'If you have any questions and/or comments about the functioning of the Dataset Register, please contact <a href="mailto:info@nationaalarchief.nl?subject=Datasetregister">info@nationaalarchief.nl</a>.',

    # faq-gebruikers.php
    'Veelgestelde vragen over het Datasetregister door dataset gebruikers bij erfgoedinstellingen en aggregators'=>'Frequently asked questions about the Dataset Register by dataset users at heritage institutions and aggregators',
    'Welke datasets stelt het Datasetregister beschikbaar?'=>'Which datasets does the Dataset Register make available?',
    'Het Datasetregister stelt <b>geen</b> datasets ter beschikking. Datasets (in de vorm van datadump of API\'s) staan bij de bron (=de erfgoedinstelling) of op een open data platform waar de erfgoedinstelling gebruik van maakt.'=>'The Dataset Register makes <b>no</b> datasets available. Data sets (in the form of data dump or APIs) are stored at the source (= the heritage institution) or on an open data platform that the heritage institution uses.',
    'Het Datasetregister levert op basis van zoekvragen URI\'s van datasetbeschrijvingen op, deze datasetbeschrijvingen bevatten verwijzingen naar de datasets.'=>'The Dataset Register provides URIs of dataset descriptions based on search queries. These dataset descriptions contain references to the datasets.',
    'Welke datasetbeschrijvingen stelt het Datasetregister beschikbaar?'=>'Which dataset descriptions does the Dataset Register make available?',
    'Het Datasetregister stelt <b>geen</b> datasetbeschrijvingen ter beschikking. Datasetbeschrijvingen staan bij de bron (=de erfgoedinstelling) of op een open data platform waar de erfgoedinstelling gebruik van maakt.'=>'The Dataset Register makes <b>no</b> dataset descriptions available. Dataset descriptions are available at the source (= the heritage institution) or on an open data platform that the heritage institution uses.',
    'OK, het Datasetregister bevat wel datasetbeschrijvingen, maar dit is puur als cache en om de datasetbeschrijvingen efficiënt te kunnen doorzoeken. Het Datasetregister levert op basis van zoekvragen URI\'s van datasetbeschrijvingen bij de bron op.'=>'OK, the Dataset Register does contain dataset descriptions, but this is purely as a cache and to efficiently search the dataset descriptions. The Dataset Register provides URIs of dataset descriptions at the source on the basis of queries.',
    'Hoe kan ik de datasetbeschrijvingen doorzoeken?'=>'How can I search the dataset descriptions?',
    'De datasetbeschrijvingen zijn via de web-GUI op het SPARQL-endpoint van de triplestore te doorzoeken. De datasetbeschrijvingen zijn opgeslagen op basis van het DCAT vocabulair.'=>'The dataset descriptions are searchable via the web GUI on the SPARQL endpoint of the triplestore. The dataset descriptions are stored on the basis of the DCAT vocabulary.',
    'Kan ik het Datasetregister nu al gebruiken?'=>'Can I already use the Dataset Register?',
    'Jazeker! De definitie van wat voor informatie er in de datasetbeschrijving opgenomen dient te worden ligt vast. Ook het mechanisme om datasetbeschrijvingen aan te melden en de opslag van datasetbeschrijvingen in een triplestore zijn operationeel. Als dataset beheerder kun je dus beginen met het beschrijven van de beschikbare datasets, bekijken waar de datasetbeschrijvingen kunnen worden gepubliceerd en deze aanmelden. Veelal betekent dit ook contact zoeken met uw software leverancier.'=>'Yes, of course! The definition of what information should be included in the dataset description is fixed. The mechanism to register dataset descriptions and the storage of dataset descriptions in a triplestore are also operational. As a dataset administrator you can therefore start by describing the available datasets, see where the dataset descriptions can be published and register them. This often also means contacting your software supplier.',
    'Als je een stap verder wilt gaan, dan kun je het Datasetregister in je collectiebeheersysteem implementeren zodat collectiebeheerders ermee aan de slag kunnen. Wij ondersteunen je hier graag bij.'=>'If you want to go a step further, you can implement the Dataset Register in your collection management system so that collection managers can get started with it. We are happy to support you with this.',

    # faq-ontwikkelaars.php
    'Veelgestelde vragen over het Datasetregister door ontwikkelaars van erfgoed software'=>'Frequently asked questions about the Dataset Register by developers of heritage software',
    'Waarom zijn machine-leesbare datasetbeschrijvingen belangrijk?'=>'Why are machine-readable dataset descriptions important?',
    'Om machines de datasetbeschrijvingen te laten begrijpen is het van belang dat deze niet alleen leesbaar is voor de mens, maar ook voor de machine. Standaarden als <a href="https://schema.org/Dataset">schema.org/Dataset</a> helpen om de semantiek van de datasetbeschrijvingen vast te leggen. Als er rijke informatie worden geboden verbeterd de vindbaarheid.'=>'In order for machines to understand the dataset descriptions, it is important that it is not only readable by humans, but also by the machine. Standards like <a href="https://schema.org/Dataset">schema.org/Dataset</a> help to capture the semantics of the dataset descriptions. If rich information is provided, findability improves.',
    'Welke informatie bevat een datasetbeschrijving?'=>'What information does a dataset description contain?',
    'De informatie die verplicht en aanbevolen is - op basis van <a href="https://schema.org/Dataset">schema.org/Dataset</a> - staat beschreven in een <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/">requirements document</a>.'=>'The information that is required and recommended - based on <a href="https://schema.org/Dataset">schema.org/Dataset</a> - is described in a <a href="https:// network-digital-heritage.github.io/requirements-datasets/">requirements document</a>.',
    'Onderstaande afbeelding geeft de gelaagdheid aan van datasetbeschrijvingen:'=>'The image below indicates the layering of dataset descriptions:',
    'Op welke wijze dienen datasetbeschrijvingen gepubliceerd te worden?'=>'How should dataset descriptions be published?',
    'Inhoudelijk dient de dataset beschrijving te voldoen aan een standaard als <a href="https://schema.org/Dataset">schema.org/Dataset</a> (en later DCAT). Qua weergave, ook wel serialisatie genoemd, zijn er verschillende mogelijkheden:'=>'In terms of content, the dataset description must comply with a standard such as <a href="https://schema.org/Dataset">schema.org/Dataset</a> (and later DCAT). In terms of display, also called serialization, there are several possibilities:',
    'opgenomen in een HTML als <a href="https://schema.org/docs/gs.html">microdata</a> of <a href="https://www.w3.org/TR/xhtml-rdfa-primer/">RDFa</a>;'=>'included in an HTML as <a href="https://schema.org/docs/gs.html">microdata</a> or <a href="https://www.w3.org/TR/xhtml- rdfa primer/">RDFa</a>;',
    'als &lt;script type="application/ld+json"&gt; blok met <a href="https://json-ld.org/">JSON-LD</a> een HTML pagina (aan serverkant ingevoegd of via Javascript aan client-zijde geïnjecteerd);'=>'as &lt;script type="application/ld+json"&gt; block containing <a href="https://json-ld.org/">JSON-LD</a> an HTML page (inserted on the server side or injected via Javascript on the client side);',
    'als los RDF resource.'=>'as a separate RDF resource.',
    'De meeste (geautomatiseerde) gebruiker verwachten de datasetbeschrijving "ge-embed" in de HTML painga. Spiders van zoekmachines zoals Google volgen gelinkte JSON-LD bestanden <b>niet</b>. Ook, via Javascript geïnjecteerde JSON-LD wordt door de meeste spiders niet opgemerkt. Er zijn meer serialisaties van RDF, zoals RDF/XML en Turtle. Spiders van zoekmachines als Google ondersteunen alleen microdata, RDFa en JSON-LD (deze laatste vorm wordt door Google geadviseerd). Omdat vindbaarheid een belangrijk aspect is wordt het gebruik van inline JSON-LD geadviseerd. Echter, dit laat onverlet dat dataset beschrijvingen <b>ook</b> in andere serialisatieformaten of via een aparte resource (op basis van content negotiation) worden gepubliceerd.'=>'Most (automated) users expect the dataset description to be "embedded" in the HTML page. Spiders from search engines like Google <b>do not</b> track linked JSON-LD files. Also, Javascript-injected JSON-LD goes undetected by most spiders. There are more serializations of RDF, such as RDF/XML and Turtle. Spiders from search engines like Google only support microdata, RDFa and JSON-LD (the latter form is recommended by Google). Because findability is an important aspect, the use of inline JSON-LD is recommended. However, this does not affect the fact that dataset descriptions are <b>also</b> published in other serialization formats or via a separate resource (based on content negotiation).',
    'Het Datasetregister ondersteunt ook datacatalogs. Deze set van datasets geeft in één keer informatie over alle beschikbare datasets van een organisatie.'=>'The Dataset Register also supports data catalogs. This set of datasets provides information about all available datasets of an organization in one go.',
    'Welke functies biedt het Datasetregister?'=>'What functions does the Dataset Register offer?',
    'Het Datasetregister biedt, naast website, een tweetal toegangen: een REST API en een SPARL endpoint.'=>'In addition to the website, the Dataset Register offers two access points: a REST API and a SPARL endpoint.',
    'Hoe kan een dataset aangemeld worden bij het Datasetregister?'=>'How can a dataset be registered with the Datasetregister?',
    'Via de REST API kan een URL worden aangemeld van een pagina waar een datasetbeschrijving wordt gepubliceerd, een directe URL van een RDF bestand met datasetbeschrijving of een URL van een datacatalog.'=>'Via the REST API, a URL can be submitted of a page where a dataset description is published, a direct URL of an RDF file with dataset description or a URL of a data catalog.',
    'Via deze website kun je via de browser een URL van een datasetbechrijving of datacatalogus aanmelden, hierbij wordt er gebruik gemaakt van de REST API.'=>'Via this website you can submit a URL of a dataset description or data catalog via the browser, using the REST API.',
    'Kan iedereen een datasetbeschrijving toevoegen aan het Datasetregister?'=>'Can anyone add a dataset description to the Datasets Register?',
    'Het aanmelden van datasets via de REST API werkt op basis van een <a href="https://triplestore.netwerkdigitaalerfgoed.nl/resource?uri=https:%2F%2Fdata.netwerkdigitaalerfgoed.nl%2Fregistry%2Fallowed_domain_names&amp;role=context" target="_blank">lijst van toegestane domeinen</a>. Datasetbechrijvingen (en datacatalogi) die afkomstig zijn van domeinen op deze lijst worden toegevoegd.'=>'',
    'Ontbreekt er een domeinnaam van een erfgoedinstelling of leverancier, neem dan contact op.'=>'If a domain name of a heritage institution or supplier is missing, please contact us.',
    'Hoe kan een datasetbeschrijving gecontroleerd worden?'=>'How can a dataset description be checked?',
    'Via de REST API kan de datasetbeschrijving van een datasetbeschrijving worden gecontroleerd op de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a>.'=>'Via the REST API, the dataset description of a dataset description can be checked against the <a href="https://netwerk-digital-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a>.',
    'Je kunt de datasetbeschrijving ook controleren met behulp van de algemenere <a href="https://validator.schema.org/">Schema Markup Validator</a>. Geef hier de URL op van de (online) pagina waarin de datasetbeschrijving is opgenomen of plak een codefragment om de test uit te voeren.'=>'You can also check the dataset description using the more general <a href="https://validator.schema.org/">Schema Markup Validator</a>. Enter here the URL of the (online) page that contains the dataset description or paste a code snippet to run the test.',
    'Hoe werkt het Datasetregister, technisch?'=>'How does the Dataset Register work, technically?',
    'Het Datasetregister beoogt een verwijzer naar datasets te worden. Hiertoe crawlt het Datasetregister de URL\'s van aangemelde pagina\'s met datasetbeschrijvingen.'=>'The Dataset Register aims to become a pointer to datasets. To do this, the Dataset Register crawls the URLs of logged-in pages with dataset descriptions.',
    'De datasetbeschrijvingen worden gevalideerd en na conversie opgeslagen in een triplestore.'=>'The dataset descriptions are validated and stored in a triplestore after conversion.',
    'Onderstaand ontwerp toont de <i>high-level</i> componenten:'=>'The design below shows the <i>high-level</i> components:',
    'Hoe kan ik het Datasetregister uitproberen?'=>'How can I try out the Dataset Register?',
    'Via deze website kun je datasetbeschrijvingen aanmelden en doorzoeken.'=>'You can submit and search dataset descriptions via this website.',
    'Hoe kan ik de API van het Datasetregister aanspreken?'=>'How can I access the Dataset Register API?',
    'De URL van de Datasetregister API is https://datasetregister.netwerkdigitaalerfgoed.nl/api/'=>'The URL of the Datasetregister API is https://datasetregister.netwerkdigitaalerfgoed.nl/api/',
    'In de <a href="https://github.com/netwerk-digitaal-erfgoed/registry-poc/blob/master/api-4.md">beschrijving van de API</a> vind je informatie over het endpoint.'=>'In the <a href="https://github.com/network-digital-erfgoed/registry-poc/blob/master/api-4.md">description of the API</a> you will find information about the endpoint.',
    'Hoe kan ik vanuit mijn collectiebeheersysteem gebruikmaken van het Datasetregister?'=>'How can I use the Dataset Register from my collection management system?',
    'Het gebruik van de API staat open voor alle erfgoedinstellingen en hun leveranciers.'=>'The use of the API is open to all heritage institutions and their suppliers.',
    'Wie maakt en beheert het Datasetregister?'=>'Who creates and manages the Dataset Register?',
    'Jazeker! Het Datasetregister wordt nog doorontwikkeld en nog verder gevuld, maar nu al te gebruiken. We horen dan ook graag wat je ervan vindt. Bijvoorbeeld: zijn de zoekmogelijkheden toereikend? Is de API bruikbaar?'=>'Yes, of course! The Dataset Register is still being developed and filled in even further, but can already be used. We\'d love to hear what you think. For example: are the search options sufficient? Is the API usable?',

    # contact.php
    'Heb je vragen over het Datasetregister, problemen of wensen?'=>'Do you have questions about the Dataset Register, problems or wishes?',
	'Neem dan contact op met <a href="mailto:info@nationaalarchief.nl?subject=Datasetregister">info@nationaalarchief.nl</a>.'=>'Please contact <a href="mailto:info@nationaalarchief.nl?subject=Datasetregister">info@nationaalarchief.nl</a>.',

    # privacy.php
    'Het Datasetregister is het resultaat van de samenwerking binnen het Netwerk Digitaal Erfgoed en wordt beheerd en onderhouden door het Nationaal Archief. Het verwerken, waaronder begrepen publiceren, van de namen van natuurlijke personen heeft ten doel kenbaar te maken dat deze persoon de contactpersoon, uitgever en/of maker van de betreffende dataset is. De wijze waarop het Nationaal Archief persoonsgegevens verwerkt is vastgelegd in een <a href="https://www.nationaalarchief.nl/privacybeleid-nationaal-archief">Privacybeleid</a> en <a href="https://www.nationaalarchief.nl/privacyreglement-nationaal-archief">Privacyreglement</a>.'=>'The Dataset Register is the result of collaboration within the Digital Heritage Network and is managed and maintained by the National Archives. The purpose of processing, including publishing, the names of natural persons is to indicate that this person is the contact person, publisher and/or creator of the relevant dataset. The manner in which the National Archives processes personal data is laid down in a <a href="https://www.nationaalarchief.nl/privacybeleid-nationaal-archief">Privacy Policy</a> and <a href="https://www.nationaalarchief.nl/privacyreglement-nationaal-archief">Privacy Regulations</a>.',
    'Onze gegevens'=>'Our data',
    'Deze website is eigendom van en wordt beheerd en onderhouden door het Nationaal Archief. Je kunt ons bereiken via <a href="mailto:info@nationaalarchief.nl?subjec=Datasetregister">info@nationaalarchief.nl</a>.'=>'This website is owned, managed and maintained by the National Archives. You can reach us via <a href="mailto:info@nationaalarchief.nl?subjec=Datasetregister">info@nationaalarchief.nl</a>.',
    'Deze dienst'=>'This service',
    'De website en de API van het Datasetregister maken geen gebruik van cookies voor tracking of analytische doeleinden.'=>'The Dataset Register website and API do not use cookies for tracking or analytical purposes.',
    'Bevragingen van website en API worden vastgelegd in een logbestand. Deze technische informatie, waaronder het IP-adres dat de bevraging doet, is alleen toegankelijk door technische beheerders en wordt gebruikt om inzicht te krijgen in het gebruik van het Datasetregister.'=>'Website and API queries are recorded in a log file. This technical information, including the IP address that makes the query, is only accessible by technical administrators and is used to gain insight into the use of the Dataset Register.',

    # apidoc.php
    'Datasetregister API specificatie'=>'Dataset Register API specification',
    'De Datasetregister API is bedoeld om online pagina\'s met datasetbeschrijving aan te melden en te valideren. De API beschrijving is op basis van een Open API specification beschikbaar via <a href="https://datasetregister.netwerkdigitaalerfgoed.nl/api/static/index.html" target="_blank">Swagger UI</a>.'=>'The Datasetregister API is intended to register and validate online pages with dataset description. The API description is available based on an Open API specification via <a href="https://datasetregister.netwerkdigitaalerfgoed.nl/api/static/index.html" target="_blank">Swagger UI</a>.',
    'Voorbeeld aanmelding URL van pagina met datasetbeschrijving via API met Curl'=>'Sample login URL of dataset description page via API with Curl',
    'Voorbeeld validatie datasetbeschrijving via API met Curl'=>'Example validation dataset description via API with Curl',

    # validate.php
    'Valideer een datasetbeschrijving'=>'Validate a dataset description',
    'Voer een URL in van een pagina met een schema.org/Dataset of schema.org/DataCatalog (inline JSON-LD of direct RDF) om deze via de <a href="apidoc.php">Datasetregister API</a> te valideren. Er wordt dan gecontroleerd de aangetroffen datasetbeschrijving (of datasetbeschrijvingen) voldoen aan de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/" target="_blank">dataset requirements</a>. De validate wordt uitgevoerd op basis van een <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/shacl/register.ttl">SHACL bestand</a>. Als de op de URL aangetroffen dataset niet voldoet, dan wordt het resultaat van de SHACL validatie getoond.'=>'Enter a URL of a page containing a schema.org/Dataset or schema.org/DataCatalog (inline JSON-LD or direct RDF) to access it via the <a href="apidoc.php?lang=en">Datasetregister API</a> validate. It is then checked that the found dataset description (or dataset descriptions) meet the <a href="https://netwerk-digital-erfgoed.github.io/requirements-datasets/" target="_blank">dataset requirements</a>. The validate is performed on the basis of a <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/shacl/register.ttl">SHACL file</a>. If the dataset found on the URL is not satisfactory, the result of the SHACL validation is displayed.',
    'URL van pagina met datasetbeschrijving (of datacatalogus)'=>'URL of dataset description page (or data catalog)',
    'Datasetbeschrijving valideren'=>'Validate dataset description',
    'Datasetbeschrijving aanmelden'=>'Register dataset description',
    'Klik om de SHACL validatie resultaten te bekijken'=>'Click to view the SHACL validation results',
    'Alle datasetbeschrijvingen op de ingediende URL zijn geldig volgens de <a href=\"https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/\">vereisten voor datasets</a>.'=>'All dataset descriptions on the submitted URL are valid according to the <a href=\"https://netwerk-digital-erfgoed.github.io/requirements-datasets/\">dataset requirements</a>.',
    'Een of meer datasetbeschrijvingen zijn ongeldig volgens de <a href=\"https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/\">vereisten voor datasets</a>.'=>'One or more dataset descriptions are invalid according to the <a href=\"https://network-digital-heritage.github.io/requirements-datasets/\">dataset requirements</a>.',
    'De URL kan niet worden gevonden.'=>'The URL could not be found.',
    'De URL kan worden gevonden, maar bevat geen datasets.'=>'The URL can be found, but contains no datasets.',
    'Er heeft zich een onbekende fout voorgedaan. <a href=\"contact.php\">Neem contact met ons op</a> en geef daarbij de door u ingevulde URL op.'=>'An unknown error has occurred. <a href=\"contact.php?lang=en\">Contact us</a> with the URL you entered.',
    'overtredingen'=>'violations',
    'overtreding'=>'violation',
    'waarschuwingen'=>'warnings',
    'waarschuwing'=>'warning',

    # viaurl.php
    'Meld een datasetbeschrijving aan'=>'Submit a dataset description',
    'Voer een URL in van een pagina met een schema.org/Dataset of schema.org/DataCatalog (inline JSON-LD of direct RDF) om deze via de <a href="apidoc.php">Datasetregister API</a> aan te melden. Als de domeinnaam voorkomt op de lijst van toegestane domeinnamen (zie <a href="faq-ontwikkelaars.php#allowed_domain_names">FAQ</a>) en de aangetroffen datasetbeschrijving(en) voldoen aan de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/" target="_blank">dataset requirements</a> dan zullen deze in het Datasetregister worden opgenomen.'=>'Enter a URL of a page with a schema.org/Dataset or schema.org/DataCatalog (inline JSON-LD or direct RDF) to submit via the <a href="apidoc.php?lang=en">Datasetregister API</a> to report. If the domain name is on the list of allowed domain names (see <a href="faq-developers.php?lang=en#allowed_domain_names">FAQ</a>) and the dataset description(s) encountered match the <a href="https:/ /network-digital-erfgoed.github.io/requirements-datasets/" target="_blank">dataset requirements</a> then these will be included in the Dataset Register.',
    'Hier komt het resultaat van de aanroep van de aanmeld functie via de API'=>'The result of the API call will be shown here',
    'API wordt aangeroepen'=>'API is called',
    'De domeinnaam van de ingediende URL staat niet op de lijst met toegestane domeinnamen. <a href=\"/contact.php\">Neem contact met ons op</a> om de domeinnaam van uw instelling toe te voegen.'=>'The domain name of the submitted URL is not on the list of allowed domain names. <a href=\"contact.php?lang=en\">Contact us</a> to add your institution\'s domain name.',
    'Voor zover er persoonsgegevens in uw datasetbeschrijving of in uw toekomstige databeschrijvingen voorkomen geeft u – als het u zelf betreft - hierbij toestemming of – als het niet u zelf betreft – verklaart u dat u ervoor instaat dat de betrokken personen toestemming hebben gegeven voor het verwerken, waaronder begrepen publiceren, van deze gegevens ten behoeve van het datasetregister en heeft u deze personen gewezen op het <a target="_blank" href="https://www.nationaalarchief.nl/privacybeleid-nationaal-archief">privacybeleid</a> en <a target="_blank" href="https://www.nationaalarchief.nl/privacyreglement-nationaal-archief">privacyreglement</a> van het Nationaal Archief.'=>'Insofar as personal data appear in your dataset description or in your future data descriptions, you - if it concerns you - hereby give permission or - if it does not concern you yourself - hereby declare that you guarantee that the persons concerned have given permission for the processing, including publishing, of this data for the Dataset Register and you have pointed these persons to the <a target="_blank" href="https://www.nationaalarchief.nl/privacybeleid-nationaal-archief">privacy policy</ a> and <a target="_blank" href="https://www.nationaalarchief.nl/privacyRegulations-nationaal-archief">privacy regulations</a> of the National Archives.',

    # search.php
    'Doorzoek alle datasetbeschrijvingen'=>'Search all dataset descriptions',
    'Door erfgoedinstellingen aangemelde datasetbeschrijvingen worden opgeslagen in een openbare <a target="triplestore" href="https://triplestore.netwerkdigitaalerfgoed.nl/">triplestore</a> op basis van het DCAT <a href="datamodel.php">datamodel</a>. Via de <a target="datastory" href="https://datastories.demo.netwerkdigitaalerfgoed.nl/hackalod/datasetregister/">Data Stories</a> leer je hoe te zoeken middels SPARQL. Deze pagina toont een zoekinterface op het datasetregister. Ook is dit een hulpmiddel voor het maken van SPARQL queries om de datasetbeschrijvingen te doorzoeken.'=>'Dataset descriptions submitted by heritage institutions are stored in a public <a target="triplestore" href="https://triplestore.netwerkdigitaalerfgoed.nl/">triplestore</a> based on the DCAT <a href="datamodel.php?lang=en" >data model</a>. Via the <a target="datastory" href="https://datastories.demo.netwerkdigitaalerfgoed.nl/hackalod/datasetregister/">Data Stories</a> you will learn how to search using SPARQL. This page shows a search interface on the Dataset Register. It is also a tool for creating SPARQL queries to search the dataset descriptions.',
    'Zoekwoord'=>'Keyword',
    'Doorzoek'=>'Search',
    'Naam'=>'Name',
    'Omschrijving'=>'Description',
    'Steekwoorden'=>'Tags',
    'Uitgever'=>'Publisher',
    'Alle organisaties'=>'All organisations',
    'Maker'=>'Creator',
    'Formaat'=>'Format',
    'Selecteer Linked Data formaten'=>'Select Linked Data formats',
    'Selecteer SPARQL formaten'=>'Select SPARQL formats',
    'Verwijder selectie(s)'=>'Clear selection(s)',
    'Zoek datasets'=>'Search datasets',
    'Neem onderstaande SPARQL mee naar de triplestore'=>'Take the SPARQL below to the triple store',
	'De SPARQL is gekopieerd.'=>'The SPARQL has been copied.',
    'Klik de SPARQL om deze te kopieren.'=>'Click the SPARQL to copy it.',
    'Zoekresultaten'=>'Search results',
    'of'=>'or',
	'De zoekresultaat zijn gesorteerd op het aantal sterren wat een indicatie is van hoe uitgebreid de datasetbeschrijving is.'=>'The search results are sorted by the number of stars which is an indication of how extensive the dataset description is.',
	'doorzoekt namen, omschrijvingen en steekwoorden'=>'searches names, descriptions and keywords',
	'Als er meerdere zoektermen worden opgegeven dan bevatten de zoekresultaten één of meer van deze termen. Wil je dat alle zoektermen moeten voorkomen koppel de zoektermen dan met AND.'=>'If multiple search terms are specified, the search results will contain one or more of these terms. If you want all search terms to appear, link the search terms with AND.',
	'Filter op organisatie'=>'Filter by organisation',

    # datamodel.php
    'Uitleg van de dataconcepten'=>'Explanation of the data concepts',
    'Datasetbeschrijving'=>'Dataset description',
    'Wanneer de datasetbeschrijving bij de bron wordt opgehaald en gevalideerd, dan wordt deze in een eigen graaf opgeslagen op basis van <code>dcat:Dataset</code>. De URL van de graaf correspondeert met de IRI van de dataset.'=>'When the dataset description is retrieved and validated at source, it is stored in its own graph based on <code>dcat:Dataset</code>. The URL of the graph corresponds to the IRI of the dataset.',
    'Datasetbeschrijvingen die worden geleverd op basis van schema.org - zoals geadviseerd in de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a> - worden geconverteerd naar DCAT.'=>'Dataset descriptions provided from schema.org - as advised in the <a href="https://netwerk-digital-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a> - are converted to DCAT.',
    'Onderstaande tabel geeft de eigenschappen weer die in een datasetbeschrijving kunnen voorkomen:'=>'The table below shows the properties that can appear in a dataset description:',
    'Eigenschap'=>'Property',
    'Beschrijving'=>'Description',
    'Gebaseerd op'=>'Based on',
    'Organisaties'=>'Organisations',
    'Elke datasetbeschrijving heeft een <code>dct:publisher</code> en optioneel ook een of meer <code>dct:creator</code>s. Een <code>dct:publisher</code> is de organisatie die de dataset publiceert. Een <code>dct:creator</code> is de organisatie die de dataset (oorsponkelijk) heeft gemaakt.'=>'Each dataset description has a <code>dct:publisher</code> and optionally also one or more <code>dct:creator</code>s. A <code>dct:publisher</code> is the organization who publishes the dataset. A <code>dct:creator</code> is the organization that (originally) created the dataset.',
    'Organisatie hebben als type <code>foaf:Organization</code> en naast een IRI ook onderstaande eigenschappen:'=>'Organizations have as type <code>foaf:Organization</code> and in addition to an IRI also the following properties:',
    'Distributies'=>'Distributions',
    'Een datasetbeschrijving kan een of meerdere distributies bevatten. Een distributie geeft de wijze aan waarop de dataset kan worden opgehaald (als het om een bestand/datadump gaat) of bevraagd (als het op een API gaat, zoals OAI-PMH, SPARQL, enz.).'=>'A dataset description can contain one or more distributions. A distribution specifies how the dataset can be retrieved (if it is a file/data dump) or queried (if it is on an API, such as OAI-PMH, SPARQL, etc.).',
    'Onderstaande tabel geeft de eigenschappen weer die in een distributie kunnen voorkomen:'=>'The table below lists the properties that can occur in a distribution:',

    # form-definition.php
    'Beschrijving inhoud'=>'Content description',
    'Bestandsgrootte'=>'Filesize',
    'Bronvermelding'=>'Citation',
    'Creatiedatum'=>'Date of creation',
    'Data-eigenaar contact E&#8209;mail'=>'Data owner contact e-mail',
    'Data-eigenaar contact Naam'=>'Data owner contact name',
    'Data-eigenaar contact Telefoon'=>'Data owner contact phone',
    'Data-eigenaar'=>'Data owner',
    'Data-eigenaar URI'=>'Data owner URI',
    'Data-eigenaar naam'=>'Data owner name',
    'Dekking plaats/gebied'=>'Spatial coverage',
    'Dekking tijd/periode'=>'Temporal coverage',
    'Distributie'=>'Distribution',
    'Formaat'=>'Format',
    'Genre'=>'Genre',
    'Identificatie'=>'Identification',
    'Licentie'=>'License',
    'Meer informatie'=>'More information',
    'Naam datacatalogus waar dataset onderdeel van uitmaakt'=>'Name data catalog of which dataset is part',
    'Naam'=>'Name',
    'Omschrijving'=>'Description',
    'Publicatiedatum'=>'Date of publication',
    'Soort'=>'Type',
    'Taal metadata'=>'Language metadata',
    'Taal'=>'Language',
    'Tag'=>'Tag',
    'URI dataset waar deze dataset op is gebaseerd'=>'URI dataset on which this dataset is based',
    'URL'=>'URL',
    'Versie'=>'Version',
    'Verstrekker contact E&#8209;mail'=>'Publisher contact email',
    'Verstrekker contact Naam'=>'Publisher contact name',
    'Verstrekker contact Telefoon'=>'Publisher contact phone',
    'Verstrekker'=>'Publisher',
    'Verstrekker URI'=>'Publisher URI',
    'Verstrekker naam'=>'Publisher name',
    'Wijzigingsdatum'=>'Data of change',

    'Beschrijving van de datasetdistributie'=>'Description of the dataset distribution',
    'Datum waarom de dataset is aangemaakt'=>'Date why the dataset was created',
    'Datum waarop de dataset is gepubliceerd'=>'Date the dataset was published',
    'Datum waarop de dataset voor het laatst is bijgewerkt'=>'Date the dataset was last updated',
    'Datum waarop de datasetdistributie is gepubliceerd'=>'Date the dataset distribution was published',
    'Datum waarop de datasetdistributie voor het laatste is bijgewerkt'=>'Date the dataset distribution was last updated',
    'De \'wervende\' beschrijving van de inhoud van de dataset'=>'The description of the contents of the dataset',
    'De IETF BCP 47 standaard taalcode van in de beschrijving gebruikte taal'=>'The IETF BCP 47 standard language code of language used in the description.',
    'De licentie die van toepassing is op de dataset'=>'The license applicable to the dataset',
    'De maker (creator) of eigenaar van de dataset'=>'The creator or owner of the dataset',
	'De URI van de maker (creator) of eigenaar van de dataset'=>'The URI of the creator or owner of the dataset',
	'De naam van de maker (creator) of eigenaar van de dataset'=>'The name of the creator or owner of the dataset',
    'De naam van de dataset'=>'The name of the data set',
    'De uitgever (publisher) van de dataset'=>'The publisher of the dataset',
	'De URI van de verstrekker (publisher) van de dataset'=>'The URI of the publisher of the dataset',
	'De naam van de verstrekker (publisher) van de dataset'=>'The name of the publisher of the dataset',
    'De unieke identificatie (URI) van de datasetbeschrijving'=>'The unique identifier (URI) of the dataset description',
    'De URI van de datacatalogus waar deze dataset deel van uit maakt'=>'The URI of the data catalog of which this dataset is part',
    'De URI van de dataset waar deze dataset op is gebaseerd'=>'The URI of the dataset on which this dataset is based',
    'De versie van de dataset'=>'The version of the dataset',
    'E-mail van de contactpersoon bij de maker van de dataset'=>'Email from the contact person at the dataset creator',
    'E-mail van de contactpersoon bij de verstrekker van de dataset'=>'Email of the contact person at the dataset provider',
    'Een identifier die duidelijk maakt op welke manier gegevens beschikbaar worden gesteld, zoals: SPARQL-endpoint, OAI-PMH-endpoint, LDF-endpoint, (gecomprimeerde) datadump'=>'An identifier that makes clear how data is made available, such as: SPARQL endpoint, OAI-PMH endpoint, LDF endpoint, (compressed) data dump',
    'Een vermelding of referentie naar een andere creatief werk'=>'A mention or reference to another creative work',
    'De IETF BCP 47 standaard taalcode van in de datasetdistributie gebruikte taal'=>'The IETF BCP 47 standard language code of language used in the dataset distribution',
    'Genre(s) waarbinnen de dataset valt'=>'Genre(s) in which the dataset falls',
    'Grootte van het bestand in bytes'=>'File size in bytes',
    'Het adres waar de datasetdistributie benaderd kan worden'=>'The address where the dataset distribution can be accessed',
    'Licentie (URI) die van toepassing is op de dataset'=>'License (URI) applicable to the dataset',
    'Media type (MIME formaat)'=>'Media type (MIME format)',
    'Naam van de contactpersoon bij de maker van de dataset'=>'Name of the contact person at the dataset creator',
    'Naam van de contactpersoon bij de verstrekker van de dataset'=>'Name of the contact person at the dataset provider',
    'Plaats of gebied waar de dataset betrekking op heeft'=>'City or area to which the dataset pertains',
    'Steekwoord (keyword/tag) die de dataset beschrijft'=>'Keyword (tag) describing the dataset',
    'Telefoonnummer van de contactpersoon bij de maker van de dataset'=>'Phone number of the contact person at the dataset creator.',
    'Telefoonnummer van de contactpersoon bij de verstrekker van de dataset'=>'Phone number of the contact person at the dataset provider',
    'Tijdsperiode waar de dataset betrekking op heeft'=>'Period of time to which the dataset relates',
    'Webpagina met meer informatie over de dataset'=>'Web page with more information about the dataset',
	'Deze waarde linkt the dataset met de beschikbare distributie(s)'=>'This property links the Dataset to available Distribution(s)',

    # form.php
    'Datasetbeschrijvingen uit uw (collectiebeheer)systeem'=>'Dataset descriptions from your (collection management) system',
    'Het beschrijven van een dataset toont grote overeenkomsten met het beschrijven van een erfgoedcollectie. Het is dan ook logisch om ook de datasets in het collectiebeheersysteem te beheren. Dicht bij de bron, want vanuit hier worden veelal ook de datasets (als bestand of als API) beschikbaar gesteld. Online publicatie van de datasetbeschrijvingen is hierdoor vaak een eenvoudige en vooral geautomatiseerde stap. Vraag bij uw leverancier wat de mogelijkheden zijn om datasetbeschrijvingen te maken en te publiceren zodat ook uw datasets beter vindbaar worden.'=>'Describing a dataset shows great similarities with describing a heritage collection. It is therefore logical to also manage the datasets in the collection management system. Close to the source, because from here the datasets (as a file or as an API) are often also made available. Online publication of the dataset descriptions is therefore often a simple and, above all, automated step. Ask your supplier about the options for creating and publishing dataset descriptions so that your datasets can also be found more easily.',
    'Maak handmatig een datasetbeschrijving'=>'Create a dataset description manually',
    'Als uw leverancier (nog) geen mogelijkheden biedt om een datasetbeschrijving te maken, dan kunt u handmatig een datasetbeschrijving maken conform de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/">requirements</a>. Als hulpmiddel is een invulformulier beschikbaar. Deze handmatige werkwijze staat los van een collectiebeheersysteem en is dus verre van ideaal.'=>'If your supplier does not (yet) offer possibilities to create a dataset description, you can manually create a dataset description in accordance with the <a href="https://netwerk-digital-erfgoed.github.io/requirements-datasets/">requirements </a>. A form is available as an aid. This manual method is separate from a collection management system and is therefore far from ideal.',
    '<strong>Let wel</strong>: het resultaat van het formulier is een datasetbeschrijving in JSON-LD, deze moet nog wel online worden gepubliceerd voordat het kan worden aangemeld bij het Datasetregister.'=>'<strong>Please note</strong>: the result of the form is a dataset description in JSON-LD, this must still be published online before it can be registered with the Dataset Register.',
    'Datasetbeschrijving formulier'=>'Dataset description form',
    'Uitleg'=>'Explanation',
    'Verplichte velden'=>'Required fields',
    'Aanbevolen velden'=>'Recommended fields',
    'Resultaat'=>'Result',
    'Vul zo veel mogelijk van de invoervelden in, minimaal de verplichte invoervelden. Via een tooltip bij het label van een veld wordt er een beschrijving gegeven van het veld, wanneer er op een label geklikt wordt dan wordt de property beschrijving op schema.org geopend. Een groene plus knop voegt een extra invoerveld of invoerveldenset (bij distributie) toe. Op het laatste tabblad kan de datasetbeschrijving in JSON-LD worden gemaakt op basis van de ingevulde waarden.'=>'Fill in as many of the input fields as possible, at least the mandatory input fields. A tooltip at the label of a field gives a description of the field, when a label is clicked, the property description is opened on schema.org. A green plus button adds an extra input field or input field set (on distribution).<br>On the last tab, the dataset description can be created in JSON-LD based on the entered values.',
    'Wilt u alleen een indruk krijgen van een datasetbeschrijving? Klik dan op <a id="dataset_examples" href="#">voorbeelddata</a> om alle invulvelden te vullen met voorbeelddata.'=>'Do you only want to get an impression of a dataset description? Then click on <a id="dataset_examples" href="#">sample data</a> to fill in all input fields with sample data.',
    'Via het formulier is niet alles mogelijk, zo kunnen er als verwerken en maker alleen nog organisatie ingevuld worden (en niet een persoon), kunnen bij velden met een uitklaplijst geen eigen waarden ingevuld worden en is er geen meertaligheid. Dit kan wel door het resultaat te bewerken in een tekstverwerker.'=>'Not everything is possible via the form, for example, only an organization can be entered as processing and maker (and not a person), fields with a drop-down list cannot be entered with their own values and there is no multilingualism. This can be done by editing the result in a text editor.',
    'Klik op de bovenstaande JSON-LD om deze te kopieren.'=>'Click the JSON-LD to copy it.',
    'Heeft u niet zelf de mogelijkheden om deze JSON-LD te publiceren?<br>Dan kunt u gebruik maken van de <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register-entries">"publicatieservice" via Github</a>.'=>'Do you not have the possibilities to publish this JSON-LD yourself?<br>Then you can use the <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register-entries">publication service via GitHub</a>.',
    'De JSON-LD is gekopieerd.'=>'The JSON LD has been copied.',

    # form-util.php
    'Maak een keuze uit de lijst'=>'Select an option from the list',
    'Nederlands'=>'Dutch',
    'Engels'=>'English',
    'Duits'=>'German',
    'Frans'=>'French',

    # faq-developers.php
    'Veelgestelde vragen over het Datasetregister door ontwikkelaars die datasets willen vinden'=>'Frequently asked questions about the Dataset Register by developers who want to find datasets',
    'Op welke wijze kan ik het Datasetregister doorzoeken?'=>'How can I search the Dataset Register?',
    'Het Datasetregister biedt toegang tot datasetbeschrijvingen van erfgoedinstellingen. Via een frequente crawl worden de datasetbeschrijvingen in schema.org/Dataset of DCAT opgehaald, getransformeerd naar DCAT en opgeslagen in een openbare triplestore. Deze triplestore - op basis van GraphDB - heeft een web-gui die is te bereiken via  <a href="https://triplestore.netwerkdigitaalerfgoed.nl/">https://triplestore.netwerkdigitaalerfgoed.nl/</a>.'=>'The Dataset Register provides access to dataset descriptions of heritage institutions. A frequent crawl retrieves the dataset descriptions in schema.org/Dataset or DCAT, transforms them into DCAT, and stores them in a public triplestore. This triplestore - based on GraphDB - has a web gui that can be reached via <a href="https://triplestore.netwerkdigitaalerfgoed.nl/">https://triplestore.netwerkdigitaalerfgoed.nl/</a>.',
    'Is er een API op het Datasetregister?'=>'Is there an API on the Dataset Register?',
    'Ja, twee zelfs. Eén is gericht op de erfgoedinstellingen (en hun IT-leveranciers) en betreft vooral het valideren en aanmelden van datasetbeschrijvingen.'=>'Yes, even two. One is aimed at the heritage institutions (and their IT suppliers) and mainly concerns the validation and registration of dataset descriptions.',
    'De tweede API is gericht op ontwikkelaars die datasets willen vinden: het <strong>SPARQL-endpoint</strong> <a href="https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry">https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry</a>.'=>'The second API is aimed at developers who want to find datasets: the <strong>SPARQL endpoint</strong> <a href="https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry">https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry</a>.',
    'Wat voor data vind ik in het Datasetregister?'=>'What kind of data can I find in the Dataset Register?',
    'Het Datasetregister bevat geen datasets, wel bevat het datasetbeschrijvingen en deze bevatten referentie naar (distributies van) data. Dit kunnen bestanden/datadumps zijn (bijvoorbeeld gecomprimeerde XML, CSV, NT bestanden) of API\'s (bijvoorbeeld OAI-PMH, SPARQL, SRU). Wanneer een datasetbeschrijving bij de bron wordt opgehaald en gevalideerd, dan wordt deze in een eigen graaf opgeslagen op basis van <code>dcat:Dataset</code>. De URL van de graaf correspondeert met de IRI van de dataset. Datasetbeschrijvingen die worden geleverd op basis van schema.org - zoals geadviseerd in de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a> - worden geconverteerd naar <a href="https://www.w3.org/TR/vocab-dcat-2/">DCAT</a>. Meer informatie hierover op de <a href="datamodel.php">datamodel-pagina</a>.'=>'The Dataset register does not contain datasets, but it does contain dataset descriptions and these contain references to (distributions of) data. These can be files/data dumps (eg compressed XML, CSV, NT files) or APIs (eg OAI-PMH, SPARQL, SRU). When a dataset description is retrieved and validated from source, it is stored in its own graph based on <code>dcat:Dataset</code>. The URL of the graph corresponds to the IRI of the dataset. Dataset descriptions provided from schema.org - as advised in the <a href="https://netwerk-digital-erfgoed.github.io/requirements-datasets/">Requirements for Datasets</a> - are converted to <a href="https://www.w3.org/TR/vocab-dcat-2/">DCAT</a>.  You\'ll find more information on this topic on the <a href="datamodel.php?lang=en">datamodel page</a>.',
    'Zijn er voorbeelden van SPARQL queries?'=>'Are there examples of SPARQL queries?',
    'Eenvoudige voorbeelden van zoek queries vindt je op de <a href="search.php">Doorzoek</a> pagina. Dit is in wezen een SPARQL-generator die op basis van je zoekvraag een SPARQL-query maakt en afvuurt op de triplestore. Je vindt er ook een link om de gegenereerde SPARQL-query in de web-gui van de triplestore te openen.'=>'Simple examples of search queries can be found on the <a href="search.php">Search</a> page. This is essentially a SPARQL generator that creates a SPARQL query based on your query and fires it at the triplestore. You will also find a link to open the generated SPARQL query in the triplestore web gui.',
    'Een andere manier om gevoel te krijgen bij de mogelijkheden is de <a href="https://datastories.demo.netwerkdigitaalerfgoed.nl/hackalod/datasetregister/">Data Stories</a>. Alleen nog beschikbaar in het Nederlands, maar via de blauwwe pijl boven de resultaat tabellen tover je de SPARQL-query naar voren waarmee de gegevens voor tabel eronder zijn verkregen. Pas de query aan en je ziet gelijk het resultaat!'=>'Another way to get a feel for the possibilities is the <a href="https://datastories.demo.netwerkdigitaalerfgoed.nl/hackalod/datasetregister/">Data Stories</a>. Only available in Dutch, but via the blue arrow above the result tables you conjure up the SPARQL query with which the data for the table below is obtained. Modify the query and you will immediately see the result!',
    'Wat mag ik met de data uit het Datasetregister?'=>'What am I allowed to do with the data from the Dataset Register?',
    'Het gebruik van het SPARQL-endpoint staat open voor iedereen, zonder enige drempel. De datasetbeschrijvingen zelf worden door erfgoedinstellingen onder een open licentie beschikbaar gesteld. Je vindt dit terug in de verplichte property <code>schema:license</code>. De distributies binnen een dataset (dus de daadwerkelijke data) kunnen onderhevig zijn aan een meer restrictieve licentie.'=>'The use of the SPARQL endpoint is open to everyone, without any barriers. The dataset descriptions themselves are made available by heritage institutions under an open license. You can find this in the mandatory property <code>schema:license</code>. The distributions within a dataset (ie the actual data) may be subject to a more restrictive license.',
    'Ga je aan de slag met het zoeken van datasetbeschrijvingen en het SPARQL-endpoint, laat het weten, zodat we je op de hoogte kunnen houden van ontwikkelingen, updates en beschikbaarheid.'=>'If you\'re getting started looking for dataset descriptions and the SPARQL endpoint, let us know so we can keep you informed of developments, updates and availability.',

	# validate-post.php
	
	'Voer de inhoud van een datasetbeschrijving (of datacatalogus) in RDF in om deze via de <a href="apidoc.php">Datasetregister API</a> te valideren en selecteer het type RDF. Er wordt dan gecontroleerd of deze voldoet aan de <a href="https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/" target="_blank">dataset requirements</a>. De validate wordt uitgevoerd op basis van een <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/shacl/register.ttl">SHACL bestand</a>. Als de aangeleverde RDF niet voldoet, dan wordt het resultaat van de SHACL validatie getoond.'=>'Enter the contents of a dataset description (or catalog) in RDF to validate it via the <a href="apidoc.php">Dataset Register API</a>. It is then checked whether it meets the <a href="https://netwerk-digital-erfgoed.github.io/requirements-datasets/" target="_blank">dataset requirements</a>. The validation is performed on the basis of a <a href="https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/shacl/register.ttl">SHACL file</a>. If the supplied RDF does not comply, the result of the SHACL validation is shown.',
	'De datasetbeschrijving wordt niet opgeslagen of toegevoegd aan het Dataset Register. Via de <a href="viaurl.php">Meld aan</a> pagina kan een URL van een online gepubliceerde datasetbeschrijving worden aangemeld.'=>'The dataset description (or catalog) is not saved or added to the Dataset Register. A URL of a dataset description published online can be registered via the <a href="viaurl.php">Submit</a> page.',
	'Inhoud van de datasetbeschrijving (of datacatalogus)'=>'Contents of the dataset description (or catalog)',
	'Typering van de inhoud' => 'Content-type',
	'Directe datasetbeschrijving validatie'=>'Direct dataset description validation',
	'Staat de datasetbeschrijving nog niet online, plak dan de RDF van de datasetbeschrijving in de <a href="validate-post.php">directe validatie</a> pagina.'=>'If the dataset description is not yet online, paste the RDF of the dataset description into the <a href="validate-post.php">direct validation</a> page.',
	'Staat de datasetbeschrijving al online, plak dan de URL van de datasetbeschrijving in de <a href="validate.php">validatie</a> pagina.'=>'If the dataset description is already online, paste the URL of the dataset description into the <a href="validate.php">validation</a> page.',
	
    # show.php
	
	'De opgegeven URI is ongeldig'=>'The provided URI is invalid',
	'Metadata'=>'Metadata',
	'Geregistreerde URL'=>'Registered URL',
	'Registratiedatum'=>'Registration date',
	'Laatste cache update'=>'Last cache update',
	'Beoordeling (25-100)'=>'Rating (25-100)',
	'Missende eigenschappen'=>'Missing properties',
	'Terug naar zoekresultaten'=>'Back to search results',
	'Doorzoek het Dataset Register'=>'Search the Datasetregister',
	'Bekijk datasets binnen deze datacatalog'=>'View the datasets of this datacatalog',
	
	# catalog.php
	
	'De volgende'=>'The following',
	'datasets maken onderdeel uit '=>'datasets are part of'
);


function t($token) {
    global $translations_nl_en;

    if (!isset($_GET["lang"]) || $_GET["lang"]!="en") {
        return $token;
    }
    $lang="en";
    if ( !isset($translations_nl_en[$token]) ) {
		error_log("WARN: no translation_nl_en for '$token'");
        return $token;
    } else {
        return $translations_nl_en[$token];
    }
}

function l() {
    if (isset($_GET["lang"]) && $_GET["lang"]=="en") {
        return "?lang=en";
    }
}
